# docker-compose.yml

# This file is for production mode only.

services:
  web_ai:
    build: .
    image: cornatul/webai.ai
    container_name: web_ai_server
    restart: always
    ports:
      - "6969:6969"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=${ENVIRONMENT:-production}
    command: >
      sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port 6969 --workers 4 --log-level info;
      "
